{"nick":"node-slack-bot","date":"2019-12-10T00:09:01.145Z","type":"part"}
{"nick":"node-slack-bot","date":"2019-12-10T00:09:13.079Z","type":"join"}
{"nick":"node-slack-bot","date":"2019-12-10T08:25:36.914Z","type":"part"}
{"nick":"node-slack-bot","date":"2019-12-10T08:26:00.370Z","type":"join"}
{"nick":"sxa","date":"2019-12-10T11:21:39.134Z","type":"join"}
{"nick":"targos","message":"Is the build WG aware of the weird connection issues there are with Jenkins?","date":"2019-12-10T13:21:57.295Z","type":"message"}
{"nick":"targos","message":"`FATAL: Channel \"unknown\": Remote call on JNLP4-connect connection from 58.96.3ca9.ip4.static.sl-reverse.com/169.60.150.88:40292 failed. The channel is closing down or has closed down`","date":"2019-12-10T13:22:04.416Z","type":"message"}
{"nick":"targos","message":"Also, \"Resume build\" is gone?","date":"2019-12-10T13:22:48.286Z","type":"message"}
{"nick":"node-slack-bot","date":"2019-12-10T16:33:57.712Z","type":"part"}
{"nick":"node-slack-bot","date":"2019-12-10T16:34:09.488Z","type":"join"}
{"nick":"mmarchini","message":"I think it was renamed to \"Retry\"?","date":"2019-12-10T17:24:49.750Z","type":"message"}
{"nick":"mmarchini","message":"At least that's the button I just pressed ¯\\_(ツ)_/¯","date":"2019-12-10T17:25:16.918Z","type":"message"}
{"nick":"Trott","message":"Retry is different, or at least behaves differently when I've tried it. Resume Build is still there.. But Resume Build won't show up for certain types of failures, unfortunately. In those cases, you need to either use Resume Build on a prior instance of the test run, or do a full Rebuild or Retry.","date":"2019-12-10T18:04:59.849Z","type":"message"}
{"nick":"sxa","reason":"Ping timeout: 240 seconds","date":"2019-12-10T19:52:17.174Z","type":"quit"}
