{"nick":"TrentonAdams","message":"I've registered error handlers, and I'm throwing an exception in a router.get(path, function (req, res, next){  /* throw here */}).  Not only is my error handler not returning json to the caller, but it's rendering an html page","date":"2018-05-09T00:16:05.030Z","type":"message"}
{"nick":"TrentonAdams","message":"that is to say that express is rendering html, not my error handler","date":"2018-05-09T00:16:46.865Z","type":"message"}
{"nick":"TrentonAdams","message":"It is configured to use ejs, so I'm guessing it's somehow automatically doing that, but it should be hitting my handler and it's not.","date":"2018-05-09T00:17:14.473Z","type":"message"}
{"nick":"lilmonkey`","date":"2018-05-09T02:02:05.423Z","type":"join"}
{"nick":"lilmonkey`","reason":"Changing host","date":"2018-05-09T02:02:05.634Z","type":"quit"}
{"nick":"lilmonkey`","date":"2018-05-09T02:02:05.635Z","type":"join"}
{"nick":"lilmonkey","reason":"Ping timeout: 260 seconds","date":"2018-05-09T02:05:54.675Z","type":"quit"}
{"nick":"Fishrock123","date":"2018-05-09T02:17:29.252Z","type":"join"}
{"nick":"Roughy","reason":"Quit: Meadow Fresh milk","date":"2018-05-09T03:05:06.551Z","type":"quit"}
{"nick":"ericx2x","reason":"Remote host closed the connection","date":"2018-05-09T03:35:18.796Z","type":"quit"}
{"nick":"ericx2x","date":"2018-05-09T03:52:04.519Z","type":"join"}
{"nick":"ericx2x","reason":"Ping timeout: 246 seconds","date":"2018-05-09T03:56:17.402Z","type":"quit"}
{"nick":"Fishrock123","reason":"Remote host closed the connection","date":"2018-05-09T04:09:50.675Z","type":"quit"}
{"nick":"Arcarc","date":"2018-05-09T04:26:01.226Z","type":"join"}
{"nick":"Fishrock123","date":"2018-05-09T04:51:24.220Z","type":"join"}
{"nick":"ericx2x","date":"2018-05-09T04:57:49.456Z","type":"join"}
{"nick":"ericx2x","reason":"Ping timeout: 246 seconds","date":"2018-05-09T05:02:05.421Z","type":"quit"}
{"nick":"Fishrock123","reason":"Remote host closed the connection","date":"2018-05-09T05:06:37.005Z","type":"quit"}
{"nick":"Ryuno-Ki[m]","message":"TrentonAdams: Have you checked the order of how you registered the middlewares? wild guessing\u000f","date":"2018-05-09T05:21:16.241Z","type":"message"}
{"nick":"Fishrock123","date":"2018-05-09T05:36:12.419Z","type":"join"}
{"nick":"pspi","reason":"Ping timeout: 248 seconds","date":"2018-05-09T05:49:21.611Z","type":"quit"}
{"nick":"Fishrock123","reason":"Remote host closed the connection","date":"2018-05-09T05:51:42.395Z","type":"quit"}
{"nick":"Fishrock123","date":"2018-05-09T05:55:02.220Z","type":"join"}
{"nick":"ericx2x","date":"2018-05-09T06:04:04.542Z","type":"join"}
{"nick":"ericx2x","reason":"Ping timeout: 246 seconds","date":"2018-05-09T06:08:14.429Z","type":"quit"}
{"nick":"Fishrock123","reason":"Remote host closed the connection","date":"2018-05-09T06:12:49.259Z","type":"quit"}
{"nick":"Fishrock123","date":"2018-05-09T06:42:10.814Z","type":"join"}
{"nick":"Fishrock123","reason":"Client Quit","date":"2018-05-09T06:44:42.256Z","type":"quit"}
{"nick":"ericx2x","date":"2018-05-09T07:09:59.428Z","type":"join"}
{"nick":"ericx2x","reason":"Ping timeout: 246 seconds","date":"2018-05-09T07:14:23.500Z","type":"quit"}
{"nick":"commma","message":"TrentonAdams: why are you still `throw`ing instead of `next(Error)` too?","date":"2018-05-09T07:50:28.421Z","type":"message"}
{"nick":"commma","message":"also how do you send the json back in the error handler, `res.json()`?","date":"2018-05-09T07:50:45.868Z","type":"message"}
{"nick":"puddle","date":"2018-05-09T07:52:12.612Z","type":"join"}
