{"nick":"AtumT","reason":"Remote host closed the connection","date":"2018-04-24T01:00:32.074Z","type":"quit"}
{"nick":"plutoniix","date":"2018-04-24T04:06:45.315Z","type":"join"}
{"nick":"Guest59","reason":"Quit: My Mac has gone to sleep. ZZZzzz‚Ä¶","date":"2018-04-24T04:49:38.630Z","type":"quit"}
{"nick":"Guest59","date":"2018-04-24T05:09:35.271Z","type":"join"}
{"nick":"Guest59","reason":"Quit: My Mac has gone to sleep. ZZZzzz‚Ä¶","date":"2018-04-24T05:18:54.987Z","type":"quit"}
{"nick":"AtumT","date":"2018-04-24T10:09:33.520Z","type":"join"}
{"nick":"mylesborins","reason":"Quit: farewell for now","date":"2018-04-24T10:25:08.430Z","type":"quit"}
{"nick":"mylesborins","date":"2018-04-24T10:25:39.089Z","type":"join"}
{"nick":"dagobert___","date":"2018-04-24T11:18:32.684Z","type":"quit"}
{"nick":"dagobert___","date":"2018-04-24T11:18:54.239Z","type":"join"}
{"nick":"plutoniix","reason":"Quit: Leaving","date":"2018-04-24T12:50:48.207Z","type":"quit"}
{"nick":"musgravejw_","date":"2018-04-24T13:40:39.019Z","type":"quit"}
{"nick":"musgravejw_","date":"2018-04-24T13:40:53.868Z","type":"join"}
{"nick":"trungl-bot`","message":"\u00034\u0002Tree closed\u000f by buildbot@chromium.org: Tree is closed (Automatic: \"configure node.js\" on \"V8 Linux64 - node.js integration\" sigurds@chromium.org)","date":"2018-04-24T13:58:37.674Z","type":"message"}
{"nick":"trungl-bot`","message":"\u00034\u0002Tree closed\u000f by machenbach@google.com: Tree is closed (looking)","date":"2018-04-24T14:01:38.412Z","type":"message"}
{"nick":"trungl-bot`","message":"\u00034\u0002Tree closed\u000f by machenbach@google.com: Tree is closed (agrieve working on fix)","date":"2018-04-24T14:11:44.840Z","type":"message"}
{"nick":"paulfryzel","date":"2018-04-24T14:14:18.329Z","type":"quit"}
{"nick":"paulfryzel","date":"2018-04-24T14:14:36.468Z","type":"join"}
{"nick":"mmarchini","date":"2018-04-24T14:16:55.145Z","type":"quit"}
{"nick":"mmarchini","date":"2018-04-24T14:17:07.461Z","type":"join"}
{"nick":"trungl-bot`","message":"\u00033\u0002Tree opened\u000f by machenbach@google.com: open","date":"2018-04-24T14:35:56.031Z","type":"message"}
{"nick":"bradleymeck_","date":"2018-04-24T15:17:39.151Z","type":"quit"}
{"nick":"bradleymeck_","date":"2018-04-24T15:18:02.314Z","type":"join"}
{"nick":"Amadiro","date":"2018-04-24T16:23:46.462Z","type":"join"}
{"nick":"seventh","date":"2018-04-24T17:17:01.183Z","type":"join"}
{"nick":"RT|Chatzilla","reason":"Quit: ChatZilla 0.9.86.1 [Firefox 2.0.0.22pre/2010030309]","date":"2018-04-24T17:38:07.602Z","type":"quit"}
{"nick":"devsnek","message":"does the unhandled rejection callback get messed up by async/await?","date":"2018-04-24T17:53:38.352Z","type":"message"}
{"nick":"devsnek","message":"i'm seeing it being called when something throws inside an async function ","date":"2018-04-24T17:53:50.282Z","type":"message"}
{"nick":"devsnek","message":"but the async function is handled","date":"2018-04-24T17:53:55.587Z","type":"message"}
{"nick":"devsnek","message":"it gets called for each time it travels up a level of async function","date":"2018-04-24T17:54:15.821Z","type":"message"}
{"nick":"devsnek","message":"https://gc.gy/üéçüçÜüöÜ.png","date":"2018-04-24T17:54:47.565Z","type":"message"}
{"nick":"devsnek","message":"module compilation happens sync and throws","date":"2018-04-24T17:54:59.305Z","type":"message"}
{"nick":"devsnek","message":"bubbles up a level, rejection handler triggers","date":"2018-04-24T17:55:12.294Z","type":"message"}
{"nick":"devsnek","message":"bubbles up another level, handler triggers","date":"2018-04-24T17:55:17.997Z","type":"message"}
{"nick":"devsnek","message":"then finally reaches my `.catch(console.error)` and logs","date":"2018-04-24T17:55:27.995Z","type":"message"}
{"nick":"caitp","message":"devsnek: I believe there's a known issue where it gets screwed up if the rejection happens after an await","date":"2018-04-24T18:00:37.182Z","type":"message"}
{"nick":"devsnek","message":"as long as its known...","date":"2018-04-24T18:00:53.272Z","type":"message"}
{"nick":"caitp","message":"like, when an async function is first entered, and throws, it should eb detected as handed there's an outer try/catch","date":"2018-04-24T18:01:23.860Z","type":"message"}
{"nick":"caitp","message":"but it's a little bit more complicated than that too","date":"2018-04-24T18:01:40.053Z","type":"message"}
{"nick":"devsnek","message":"the theory isn't complex","date":"2018-04-24T18:02:27.870Z","type":"message"}
{"nick":"devsnek","message":"just the hundreds of lines of implementation üòâ","date":"2018-04-24T18:02:37.171Z","type":"message"}
{"nick":"caitp","message":"well, the theory doesn't really work, for a mixture of different reasons","date":"2018-04-24T18:08:32.355Z","type":"message"}
{"nick":"caitp","message":"at some point me or someone else will spend time to fix it properly","date":"2018-04-24T18:09:26.451Z","type":"message"}
{"nick":"trungl-bot`","message":"\u00034\u0002Tree closed\u000f by buildbot@chromium.org: closed (https://ci.chromium.org/buildbot/client.v8.ports/V8%20Arm%20-%20debug%20builder/13575 from 44ea425ab1ededf8776d0ada3fa694f3db64fa29)","date":"2018-04-24T18:56:02.437Z","type":"message"}
{"nick":"seventh","reason":"Remote host closed the connection","date":"2018-04-24T19:22:33.267Z","type":"quit"}
{"nick":"Guest59","date":"2018-04-24T19:27:17.388Z","type":"join"}
{"nick":"trungl-bot`","message":"\u00033\u0002Tree opened\u000f by buildbot@chromium.org: Tree is open (Automatic: ‚ô©‚Äø‚ô©)","date":"2018-04-24T20:14:38.401Z","type":"message"}
{"nick":"RT|Chatzilla","date":"2018-04-24T22:34:30.381Z","type":"join"}
{"nick":"AtumT","reason":"Remote host closed the connection","date":"2018-04-24T23:13:35.052Z","type":"quit"}
{"nick":"plutoniix","date":"2018-04-24T23:41:56.442Z","type":"join"}
